### ISSUE TITLE
good

### ISSUE THREAD

**Issue by yangchongduo** [nghiepit/next-mobx-wrapper#1]
Rất tốt, cập nhật liên tục

**Comment by yangchongduo** [comment]
Very good, continuous update

**Comment by yangchongduo** [comment]
Provider is best in next-mobx-react.

**Comment by yangchongduo** [comment]
This will still have problems with graphql.

**Comment by nghiepdev** [comment]
You can share your problem?

**Comment by yangchongduo** [comment]
Next.js example has a demo with-apollo-and-redux I want to use mobx now, but with the next-mobx-wrapper, ssr doesn't work and becomes a client-side rendering. But I don't know what the reason is?

**Comment by nghiepdev** [comment]
I think you should use `apollo-state-link` instead of `redux` or `mobx`
