### ISSUE TITLE
Example for handling client cookies when fetching api data on server

### ISSUE THREAD

**Issue by austinfox** [nghiepit/next-mobx-wrapper#2]
Thanks a bunch for releasing this wrapper, it definitely helps simplify having multiple Mobx stores while using Next.js. There is definitely a gap between the examples Next.js provides for using Mobx and implementations for real scenarios. 

While I was able to get this wrapper working with my setup, I'm having trouble figuring out the best way to fetch data for my stores on the server. In your example, you fetch data like this:

 ```javascript
fetchUser = flow(function*(id) {
    if (this.userRegistry.has(id)) {
      return;
    }

    const userPromise = yield fetch(`https://api.domain.com/users/${id}`).then(
      response => response.json(),
    );
    this.userRegistry.set(id, userPromise.data.user);
  });
```

The problem is that when this fetch is executed on the server, no cookies containing authentication tokens are sent to the api, so when you have a protected endpoint it will fail. For now, I've solved this issue by calling `fetchData(cookies)` in my stores while providing the cookies attached to the request headers in getInitialProps({ req }), something like this:

```javascript
class Hello extends React.Component {
  static async getInitialProps({ store: { userStore }, req }) {
    await userStore.fetchUser(req.headers.cookie);
    return { user: userStore.user }
  }
```

and implementing my store as follows:

```javascript
class Store extends BaseStore {
  @observable user = null;

  fetchUser = flow(function*(cookie) {
    if (this.user) return;
    const { data } = yield axios(`https://localhost:4000/user`, {
      headers: { cookie }
    });
    this.user = data;
  });
}
```

While this does work, it means that each page has to be aware that it needs to provide cookies if it is  executing a fetch in the store one the server. This feels a bit hack-y to me and I was wondering if you had some ideas for how to improve the setup and/or something we can add to this wrapper to preserve cookies and provide a "fetch" ability to stores that is isomorphic (will use cookies from req if on the server, otherwise fetch normally on the client).

**Comment by nghiepdev** [comment]
Hi @austinfox 

You can set global Axios:

```js
// helpers/axios.js
export default axios.create({
  baseURL: 'https://api.example.com'
});
```
```js
// pages/_app.js
import Cookies from 'universal-cookie';
import axios from 'helpers/axios';

static async getInitialProps({Component, ctx}) {
   const {req} = ctx;
   let cookieHeader;
   
   if(req) {
      cookieHeader = req.headers.cookie
   }

   return {
      cookieHeader
   }
}

constructor(props) {
   suprt(props);

   const cookie = new Cookies(props.cookieHeader);
   const accessToken = cookie.get('access_token');

   if(accessToken) {
      axios.defaults.headers.common['Authorization'] = accessToken;
   }
}
```

```js
// Somewhere postLogin() action, if you needed
// My recommend you should `window.reload` page after postLogin() successfully

async postLogin() {
  try {
      const {token} = await axios.post('/api/login', {username: 'admin', password: 123});

      // If you hard reload page, use don't need set here
      axios.defaults.headers.common['Authorization'] = token;

      // Set access_token cookie
      cookie.set('access_token', token, {path: '/'});
   } catch(e) {}
}
```

**Comment by iyobo** [comment]
Maybe close this?
