### ISSUE TITLE
How would you use one store's parameters in another?

### ISSUE THREAD

**Issue by designbyadrian** [nghiepit/next-mobx-wrapper#3]
In a non-NextJS app, I could basically do this:

```javascript
const oneStore = new OneStore();
const twoStore = new TwoStore(oneStore, ...);

const stores: {
  oneStore,
  twoStore,
}

<Provider {...stores} />
```

This way, I can use various parameters and observables in oneStore inside twoStore.

Is this possible with this plugin?

**Comment by nghiepdev** [comment]
Why you still want to use this plugin without `next.js`?
You can check [Combining multiple stores](https://mobx.js.org/best/store.html) doc section.
This plugin has no value without `next.js`.

**Comment by designbyadrian** [comment]
I don't, that's why I'm asking. How would I do this with your plugin?

**Comment by designbyadrian** [comment]
Please answer my question.

How do I use values from one store in another store? My example shows how this could be done with mobx, but it's not clear how to achieve the same thing with your plugin. Is it at all possible?

**Comment by nghiepdev** [comment]
In my previous answer
https://github.com/mobxjs/mobx/blob/gh-pages/docs/best/store.md#combining-multiple-stores

**Comment by designbyadrian** [comment]
This still isn't clear.

The readme has this as an example:

```javascript
// Root Store (index.js)

export { getFooStore } from './Foo';
export { getBarStore } from './Bar';

// Foo.js

class Store {
  // ...
}

export const getFooStore = getOrCreateStore('fooStore', Store);

// Bar.js

class Store {
  constructor(fooStore) {
    // how do I get fooStore from the root store?
  }
}

export const getBarStore = getOrCreateStore('barStore', Store);
```

`getOrCreateStore()` only takes the name and class name as parameters. I can't pass anything to the Store's constructor.
